### ISSUE TITLE
Double definitions

### ISSUE THREAD

**Issue by RivenSkaye** [Hejsil/dotfiles#2]
`config/env` contains two variables that get exported twice.
- `export GRADLE_USER_HOME`, the line is duplicated L39/L40
- `export GNUPGHOME` on L37 as below `$XDG_DATA_HOME`, later as below `$XDG_CONFIG_HOME` on L52

Would've PR'd it, but I'm not sure which `GNUPGHOME` definition you rely on

**Comment by Hejsil** [comment]
Good spot. I've looked it over, and I'm pretty sure that it should be CONFIG_HOME gnupg is located in. I'll just push a fix for this myself
